version: '3.8'
services:
  db:
    image: postgres:16.2-alpine3.18
    environment:
      # - postgres://postgres:123456@db:5432/metis
      POSTGRES_DB: metis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - local-networks
  metis-back:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    networks:
      - local-networks

networks:
  local-networks:
    external: true

volumes:
  postgres-database:
